version: "3.9"

services:
  db:
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: banco123
      MYSQL_DATABASE: vollmed_api
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  medicalapp:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATASOURCE_URL: jdbc:mysql://db/vollmed_api
      DATASOURCE_USERNAME: root
      DATASOURCE_PASSWORD: banco123
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8000:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: banco123

volumes:
  db_data:
